### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Walterfdh** [ImCharlesY/SepLUT#2]
How to solve this problem?

File "tools/train.py", line 169, in <module>
    main()
  File "tools/train.py", line 165, in main
    meta=meta)
  File "/home/work/test/projects/sepLUT/SepLUT/mmedit/apis/train.py", line 112, in train_model
    meta=meta)
  File "/home/work/test/projects/sepLUT/SepLUT/mmedit/apis/train.py", line 361, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/work/test/projects/sepLUT/SepLUT/mmedit/core/evaluation/eval_hooks.py", line 47, in after_train_iter
    iteration=runner.iter)
  File "/home/work/test/projects/sepLUT/SepLUT/mmedit/apis/test.py", line 48, in single_gpu_test
    **data)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/work/test/projects/sepLUT/SepLUT/seplut/model.py", line 309, in forward
    return self.forward_test(lq, gt, **kwargs)
  File "/home/work/test/projects/sepLUT/SepLUT/seplut/model.py", line 359, in forward_test
    output = self.forward_fast(lq)
  File "/home/work/test/projects/sepLUT/SepLUT/seplut/model.py", line 290, in forward_fast
    out = seplut_transform(imgs, lut3d, lut1d)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/seplut_ext/pyinterfaces.py", line 64, in seplut_transform
    return SepLUTTransformFunction.apply(img, lut3d, lut1d)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 217, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/anaconda/envs/seplut/lib/python3.7/site-packages/seplut_ext/pyinterfaces.py", line 30, in forward
    cforward(img, lut3d, lut1d, output)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by xuhangc** [comment]
Same problem, any updates? My environment is the same with the author.

**Comment by xuhangc** [comment]
I think there is something wrong with the [forward_fast](https://github.com/ImCharlesY/SepLUT/blob/49d8bc3f42c5dfc09140786d0da1e47e3adb0619/seplut/model.py#L251) during evaluation, I use forward_dummy instead and it works.

**Comment by qianyisharon** [comment]
When you configured the environment, did the seplut import be successful?
